### Read Metadata
GET http://localhost:4004/catalog/$metadata
Authorization: Basic user:

### Read Products
GET http://localhost:4004/v2/catalog/Products
Authorization: Basic user:

### Read Single Product
GET http://localhost:4004/v2/catalog/Products('195490332')
Authorization: Basic user:
# Results in this backend request:
# /sap/opu/odata/sap/EPM_REF_APPS_PROD_MAN_SRV/%5Bobject%20Object%5D?$select=Id,Name,MainCategoryId,MainCategoryName,SubCategoryId,SubCategoryName&$format=json

### Read a limited number of Products 
GET http://localhost:4004/catalog/Products?$top=5
Authorization: Basic user:

### Read only some columns
GET http://localhost:4004/catalog/Products?$top=1&$select=Id,Name
Authorization: Basic user:

### Read only some columns
GET http://localhost:4004/catalog/Products?$select=Id,Name,SubCategoryId&$top=10&$filter=SubCategoryId%20eq%20'Notebooks'
Authorization: Basic user:

### Read Products only some columns sorted ascending
GET http://localhost:4004/catalog/Products?$top=5&$select=Id,Name&$orderby=Id%20desc
Authorization: Basic user:

### Read Products Skip entries
GET http://localhost:4004/catalog/Products?$top=5&$skip=5&$select=Id,Name&$orderby=Id%20desc
Authorization: Basic user:

### Read Business Partner via SDK
GET http://localhost:4004/catalog/sdkBusinessPartner
Authorization: Basic user:
